repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Python后端检查
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: [--line-length=119, --config=service/pyproject.toml]
        files: ^service/

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args:
          [
            "--profile",
            "black",
            "--line-length=119",
            "--settings-path=service/pyproject.toml",
          ]
        files: ^service/

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=119
          - --extend-ignore=F401,W503,F541,F841,E226
        files: ^service/

  # Python类型检查 - 使用 Pyright
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406
    hooks:
      - id: pyright
        args:
          - --project=service/pyproject.toml
        files: ^service/
        entry: bash -c 'cd service && uv run --active pyright .'
