"""Capability constants and plan→capability mapping for FGA authorization."""

# Capability IDs
CAPABILITY_SANDBOX_ACCESS = "sandbox_access"
CAPABILITY_SCHEDULED_TASK_ACCESS = "scheduled_task_access"
CAPABILITY_TERMINAL_ACCESS = "terminal_access"
CAPABILITY_DEPLOYMENT_ACCESS = "deployment_access"
CAPABILITY_MODEL_TIER_STANDARD = "model_tier:standard"
CAPABILITY_MODEL_TIER_PRO = "model_tier:pro"
CAPABILITY_MODEL_TIER_ULTRA = "model_tier:ultra"

# Plan → Capabilities truth table
PLAN_CAPABILITIES: dict[str, list[str]] = {
    "free": [
        CAPABILITY_SANDBOX_ACCESS,
        CAPABILITY_SCHEDULED_TASK_ACCESS,
        CAPABILITY_TERMINAL_ACCESS,
        CAPABILITY_DEPLOYMENT_ACCESS,
    ],
    "standard": [
        CAPABILITY_SANDBOX_ACCESS,
        CAPABILITY_SCHEDULED_TASK_ACCESS,
        CAPABILITY_TERMINAL_ACCESS,
        CAPABILITY_DEPLOYMENT_ACCESS,
        CAPABILITY_MODEL_TIER_STANDARD,
    ],
    "professional": [
        CAPABILITY_SANDBOX_ACCESS,
        CAPABILITY_SCHEDULED_TASK_ACCESS,
        CAPABILITY_TERMINAL_ACCESS,
        CAPABILITY_DEPLOYMENT_ACCESS,
        CAPABILITY_MODEL_TIER_STANDARD,
        CAPABILITY_MODEL_TIER_PRO,
    ],
    "ultra": [
        CAPABILITY_SANDBOX_ACCESS,
        CAPABILITY_SCHEDULED_TASK_ACCESS,
        CAPABILITY_TERMINAL_ACCESS,
        CAPABILITY_DEPLOYMENT_ACCESS,
        CAPABILITY_MODEL_TIER_STANDARD,
        CAPABILITY_MODEL_TIER_PRO,
        CAPABILITY_MODEL_TIER_ULTRA,
    ],
}
