name: Bug Report (错误报告)
description: Create a report to help us improve. (创建一个报告以帮助我们改进。)
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        感谢您抽出时间填写此错误报告！
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? (发生了什么问题？)
      description: Also tell us, what did you expect to happen? (也请告诉我们，您期望发生什么？)
      placeholder: Tell us what you see! (告诉我们您看到了什么！)
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce (复现步骤)
      description: Please provide a clear set of steps to reproduce the bug. (请提供清晰的复现步骤。)
      placeholder: |
        1. Go to '...' (例如：进入 '...')
        2. Click on '....' (例如：点击 '....')
        3. Scroll down to '....' (例如：滚动到 '....')
        4. See error (例如：看到错误)
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior (期望的行为)
      description: A clear and concise description of what you expected to happen. (清晰简洁地描述您期望发生的情况。)
    validations:
      required: true
  - type: textarea
    id: screenshots-logs
    attributes:
      label: Screenshots or Logs (截图或日志)
      description: If applicable, add screenshots or log output to help explain your problem. Logs will be automatically formatted. (如果适用，请添加截图或日志输出以帮助解释您的问题。日志将自动格式化。)
      render: shell
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Environment Information (环境信息)
  - type: input
    id: os
    attributes:
      label: Operating System (操作系统)
      placeholder: e.g. macOS Sonoma 14.5, Windows 11, Ubuntu 22.04
    validations:
      required: false
  - type: input
    id: browser-tool-version
    attributes:
      label: Browser/Terminal/Tool Version (浏览器/终端/工具版本)
      placeholder: e.g. Chrome 125, VS Code 1.90, Terminal 2.14
    validations:
      required: false
  - type: input
    id: dependency-versions
    attributes:
      label: Relevant Dependency Versions (相关依赖版本)
      placeholder: e.g. Node.js 20.11.0, Python 3.10.12, Uni-Lab-Cloud v1.2.3
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (其他补充说明)
      description: Add any other context about the problem here. (在此处添加有关问题的任何其他上下文。)
    validations:
      required: false
