blank_issues_enabled: true
contact_links:
  - name: Ask a question or discuss (提问或讨论)
    url: https://github.com/ScienceOL/PROTIUM/discussions/new/choose
    about: Please ask and answer questions here. (请在此处提问和回答问题。)
  - name: Project Documentation (项目文档)
    url: https://github.com/ScienceOL/PROTIUM/wiki # Replace with your actual documentation link if different
    about: Check our documentation for answers. (查看我们的文档以获取答案。)
