/**
 * Emoji 工具函数
 * 用于管理普通 emoji 和卡通版本的映射
 */

/**
 * 标准 emoji 分类库 - 按照 Unicode 标准分类
 * 每个 emoji 只出现在一个分类中
 *
 * @description
 * 该分类基于 `EMOJI_TO_CARTOON_MAP` 动态生成。
 * 只有在映射表中存在的 emoji 才会被分类。
 * 分类规则通过关键字匹配实现。
 */
export const EMOJI_CATEGORIES: Record<
  string,
  { name: string; emojis: string[] }
> = {
  "emoji-face": {
    name: "😊 表情与角色",
    emojis: [
      "😀",
      "🤪",
      "☹️",
      "🤤",
      "🤧",
      "😵",
      "😄",
      "😆",
      "🤣",
      "😂",
      "🙂",
      "🙃",
      "😉",
      "😊",
      "😇",
      "🥰",
      "😍",
      "🤩",
      "😘",
      "😗",
      "😙",
      "😚",
      "😋",
      "😜",
      "😌",
      "😔",
      "😑",
      "😐",
      "😏",
      "😒",
      "🥱",
      "😓",
      "😪",
      "😴",
      "😷",
      "🤒",
      "🤕",
      "🤮",
      "🤢",
      "🤯",
      "🥵",
      "🥶",
      "😱",
      "😨",
      "😰",
      "😢",
      "😭",
      "😖",
      "😩",
      "🥺",
      "😤",
      "😡",
      "😠",
      "🤬",
      "😈",
      "👿",
      "💀",
      "💩",
      "🤡",
      "👻",
      "👽",
      "🤖",
      "😺",
      "😸",
      "😹",
      "😻",
      "😼",
      "😽",
      "🙀",
      "😿",
      "😾",
      "🙈",
      "🙉",
      "🙊",
      "😮",
      "😲",
      "🥸",
      "🤐",
      "😳",
      "😧",
      "😬",
      "🤥",
      "😎",
      "😟",
      "🥹",
      "🧐",
      "🫠",
      "🫡",
      "🫢",
      "🫣",
      "🫤",
      "🫥",
      "🫦",
      "🫨",
      "🥴",
      "🥳",
      "🤗",
      "🤓",
      "🤔",
      "🤨",
      "🤫",
      "🤭",
      "🤑",
      "🤠",
      "🙄",
      "🙁",
      "👀",
      "👁️",
      "👣",
      "😁",
      "😅",
      "😮‍💨",
      "😶‍🌫️",
      "😛",
    ],
  },
  animal: {
    name: "🐶 动物与自然",
    emojis: [
      "🐵",
      "🐔",
      "🐦",
      "🐤",
      "🦅",
      "🐝",
      "🐛",
      "🦋",
      "🐌",
      "🐞",
      "🐜",
      "🐢",
      "🐍",
      "🐙",
      "🐡",
      "🪳",
      "🐀",
      "🐂",
      "🐄",
      "🐉",
      "🐊",
      "🐋",
      "🐎",
      "🐐",
      "🐓",
      "🐕",
      "🐩",
      "🐣",
      "🐥",
      "🐦‍⬛",
      "🐬",
      "🐯",
      "🐰",
      "🐷",
      "🐸",
      "🐾",
      "🐿️",
      "🦄",
      "🦀",
      "🦆",
      "🦇",
      "🦈",
      "🦋",
      "🦍",
      "🦎",
      "🦕",
      "🦖",
      "🦘",
      "🦚",
      "🦟",
      "🦠",
      "🦦",
      "🦧",
      "🦭",
      "🦮",
      "🪰",
      "🪱",
      "🪼",
      "🫏",
    ],
  },
  food: {
    name: "🍔 食物与饮料",
    emojis: ["🍅", "🍜", "🍝", "🍳", "🍷", "🍹", "🍻", "🍾", "🍿", "🎂", "☕"],
  },
  weather: {
    name: "🌍 自然与天气",
    emojis: [
      "✨",
      "❄️",
      "⚡",
      "🔥",
      "💥",
      "💧",
      "🌱",
      "🌹",
      "🍀",
      "🌄",
      "🌅",
      "🌈",
      "🌊",
      "🌋",
      "🌍",
      "🌎",
      "🌏",
      "🌓",
      "🌗",
      "🌞",
      "🌟",
      "🌧️",
      "🌪️",
      "🌬️",
      "🍂",
      "🍃",
      "🥀",
      "☄️",
    ],
  },
  transportation: {
    name: "✈️ 交通工具",
    emojis: ["🚀", "✈️", "🚲", "🛎️", "🛬", "🛸", "🎢"],
  },
  objects: {
    name: "⏰ 日常用品",
    emojis: [
      "⏰",
      "✏️",
      "🎁",
      "🎈",
      "✅",
      "💯",
      "💔",
      "⚾",
      "💓",
      "🔔",
      "🎳",
      "🏁",
      "🎃",
      "🎆",
      "🎉",
      "🎓",
      "🎯",
      "🎰",
      "🎲",
      "🎵",
      "🎻",
      "🎾",
      "🏏",
      "🏑",
      "🏒",
      "🏓",
      "🏕️",
      "🏗️",
      "🏸",
      "💃",
      "💋",
      "💌",
      "💎",
      "💕",
      "💖",
      "💗",
      "💘",
      "💙",
      "💚",
      "💛",
      "💜",
      "💝",
      "💞",
      "💡",
      "💫",
      "💸",
      "📴",
      "📸",
      "🔋",
      "🔮",
      "🕷️",
      "🖤",
      "🗑️",
      "🤍",
      "🤎",
      "🥁",
      "🥂",
      "🥌",
      "🥎",
      "🥏",
      "🧡",
      "🩵",
      "🩶",
      "🩷",
      "🩸",
      "🪁",
      "🪃",
      "🪅",
      "🪇",
      "🪩",
      "🪫",
      "🫀",
      "🫧",
      "🚨",
      "🚩",
    ],
  },
  sign: {
    name: "©️ 符号",
    emojis: [
      "‼️",
      "⁉️",
      "☮️",
      "♈️",
      "♉️",
      "♊️",
      "♋️",
      "♌️",
      "♍️",
      "♎️",
      "♏️",
      "♐️",
      "♑️",
      "♒️",
      "♓️",
      "⚖️",
      "⚙️",
      "⛎",
      "❌",
      "❓",
      "❗",
      "❣️",
      "❤️",
      "❤️‍🔥",
      "➕",
      "🏳️",
      "🏴",
      "🆓",
      "🆕",
      "🆘",
      "🆙",
    ],
  },
  gestures: {
    name: "👍 手势",
    emojis: [
      "👋",
      "👍",
      "👎",
      "👏",
      "💪",
      "✌️",
      "🤞",
      "🙌",
      "🙏",
      "🦾",
      "🦿",
      "☝️",
    ],
  },
};

/**
 * 普通 emoji 到卡通版本的映射
 * 如果用户选择的普通 emoji 对应一个已有的卡通版本，则使用卡通版本
 */
/**
 * Unicode emoji 到动画名称的映射
 * 从 emojiAnimationConfig 中的 EMOJI_CONFIGS 派生
 * 包含所有 400+ 个支持的动画 emoji
 */
export const EMOJI_TO_CARTOON_MAP: Record<string, string> = {
  "‼️": "exclamation-double",
  "⁉️": "exclamation-question-mark",
  "⏰": "alarm",
  "☄️": "comet",
  "☔": "umbrella",
  "☕": "hot-beverage",
  "☝️": "index-finger",
  "☮️": "peace",
  "☹️": "big-frown",
  "♈️": "aries",
  "♉️": "taurus",
  "♊️": "gemini",
  "♋️": "cancer",
  "♌️": "leo",
  "♍️": "virgo",
  "♎️": "libra",
  "♏️": "scorpio",
  "♐️": "sagittarius",
  "♑️": "capricorn",
  "♒️": "aquarius",
  "♓️": "pisces",
  "⚖️": "balance-scale",
  "⚙️": "gear",
  "⚡": "electricity",
  "⚽": "soccer-ball",
  "⚾": "baseball",
  "⛈️": "cloud-with-lightning",
  "⛎": "ophiuchus",
  "✅": "check-mark",
  "✈️": "airplane-departure",
  "✌️": "victory",
  "✏️": "pencil",
  "✨": "sparkles",
  "❄️": "snowflake",
  "❌": "cross-mark",
  "❓": "question",
  "❗": "exclamation",
  "❣️": "heart-exclamation-point",
  "❤️": "red-heart",
  "❤️‍🔥": "fire-heart",
  "➕": "plus-sign",
  "🌄": "sunrise-over-mountains",
  "🌅": "sunrise",
  "🌈": "rainbow",
  "🌊": "ocean",
  "🌋": "volcano",
  "🌍": "globe-showing-europe-africa",
  "🌎": "globe-showing-americas",
  "🌏": "globe-showing-asia-australia",
  "🌓": "moon-face-first-quarter",
  "🌗": "moon-face-last-quarter",
  "🌞": "sun-with-face",
  "🌟": "glowing-star",
  "🌧️": "rain-cloud",
  "🌪️": "tornado",
  "🌬️": "wind-face",
  "🌱": "plant",
  "🌹": "rose",
  "🍀": "luck",
  "🍂": "fallen-leaf",
  "🍃": "leaves",
  "🍅": "tomato",
  "🍜": "steaming-bowl",
  "🍝": "spaghetti",
  "🍳": "cooking",
  "🍷": "wine-glass",
  "🍹": "tropical-drink",
  "🍻": "clinking-beer-mugs",
  "🍾": "bottle-with-popping-cork",
  "🍿": "popcorn",
  "🎁": "wrapped-gift",
  "🎂": "birthday-cake",
  "🎃": "jack-o-lantern",
  "🎆": "fireworks",
  "🎈": "balloon",
  "🎉": "confetti-ball",
  "🎓": "graduation-cap",
  "🎢": "roller-coaster",
  "🎯": "direct-hit",
  "🎰": "slot-machine",
  "🎲": "die",
  "🎳": "bowling",
  "🎵": "musical-notes",
  "🎻": "violin",
  "🎾": "tennis",
  "🏁": "chequered-flag",
  "🏏": "cricket-game",
  "🏑": "field-hockey",
  "🏒": "ice-hockey",
  "🏓": "ping-pong",
  "🏕️": "camping",
  "🏗️": "construction",
  "🏳️": "white-flag",
  "🏴": "black-flag",
  "🏸": "badminton",
  "🐀": "rat",
  "🐂": "ox",
  "🐄": "cow-face",
  "🐉": "dragon",
  "🐊": "crocodile",
  "🐋": "whale",
  "🐌": "snail",
  "🐍": "snake",
  "🐎": "racehorse",
  "🐐": "goat",
  "🐓": "rooster",
  "🐕": "dog",
  "🐙": "octopus",
  "🐛": "bug",
  "🐜": "ant",
  "🐝": "bee",
  "🐞": "lady-bug",
  "🐡": "blowfish",
  "🐢": "turtle",
  "🐣": "hatching-chick",
  "🐤": "baby-chick",
  "🐥": "hatched-chick",
  "🐦": "bird",
  "🐦‍⬛": "black-bird",
  "🐩": "poodle",
  "🐬": "dolphin",
  "🐯": "tiger",
  "🐰": "rabbit",
  "🐵": "monkey",
  "🐷": "pig",
  "🐸": "frog",
  "🐾": "paw-prints",
  "🐿️": "chipmunk",
  "👀": "eyes",
  "👁️": "eye",
  "👋": "wave",
  "👍": "thumbs-up",
  "👎": "thumbs-down",
  "👏": "clap",
  "👣": "footprints",
  "👻": "ghost",
  "👽": "alien",
  "👿": "imp-frown",
  "💀": "skull",
  "💃": "dancer-woman",
  "💋": "kiss",
  "💌": "love-letter",
  "💎": "gem-stone",
  "💓": "beating-heart",
  "💔": "bandaged-heart",
  "💕": "two-hearts",
  "💖": "sparkling-heart",
  "💗": "heart-grow",
  "💘": "cupid",
  "💙": "blue-heart",
  "💚": "green-heart",
  "💛": "yellow-heart",
  "💜": "purple-heart",
  "💝": "gift-heart",
  "💞": "revolving-hearts",
  "💡": "light-bulb",
  "💥": "collision",
  "💧": "droplet",
  "💩": "poop",
  "💪": "muscle",
  "💫": "dizzy",
  "💯": "100",
  "💸": "money-with-wings",
  "📴": "phone-off",
  "📸": "camera-flash",
  "🔋": "battery-full",
  "🔔": "bell",
  "🔥": "fire",
  "🔮": "crystal-ball",
  "🕷️": "spider",
  "🖤": "black-heart",
  "🗑️": "litter",
  "🤍": "white-heart",
  "🤎": "brown-heart",
  "🤐": "scrunched-mouth",
  "🤑": "money-face",
  "🤒": "sick",
  "🤓": "nerd-face",
  "🤔": "thinking-face",
  "🤕": "bandage-face",
  "🤖": "robot",
  "🤗": "hug-face",
  "🤞": "crossed-fingers",
  "🤠": "cowboy",
  "🤡": "clown",
  "🤣": "rofl",
  "🤤": "drool",
  "🤥": "liar",
  "🤧": "sneeze",
  "🤨": "raised-eyebrow",
  "🤩": "star-struck",
  "🤪": "zany-face",
  "🤫": "shushing-face",
  "🤬": "cursing",
  "🤭": "hand-over-mouth",
  "🤮": "vomit",
  "🤯": "mind-blown",
  "🥀": "wilted-flower",
  "🥁": "drum",
  "🥂": "clinking-glasses",
  "🥌": "lacrosse",
  "🥎": "softball",
  "🥏": "flying-disc",
  "🥰": "heart-face",
  "🥱": "yawn",
  "🥳": "partying-face",
  "🥴": "woozy",
  "🥵": "hot-face",
  "🥶": "cold-face",
  "🥸": "disguise",
  "🥹": "holding-back-tears",
  "🥺": "pleading",
  "🦀": "crab",
  "🦄": "unicorn",
  "🦅": "eagle",
  "🦆": "goose",
  "🦇": "bat",
  "🦈": "shark",
  "🦋": "butterfly",
  "🦍": "gorilla",
  "🦎": "lizard",
  "🦕": "dinosaur",
  "🦖": "t-rex",
  "🦘": "kangaroo",
  "🦚": "peacock",
  "🦟": "mosquito",
  "🦠": "microbe",
  "🦦": "otter",
  "🦧": "orangutan",
  "🦭": "seal",
  "🦮": "guide-dog",
  "🦾": "arm-mechanical",
  "🦿": "leg-mechanical",
  "🧐": "monocle",
  "🧡": "orange-heart",
  "🩵": "light-blue-heart",
  "🩶": "grey-heart",
  "🩷": "pink-heart",
  "🩸": "blood",
  "🪁": "kite",
  "🪃": "boomerang",
  "🪅": "pinata",
  "🪇": "maracas",
  "🪩": "mirror-ball",
  "🪫": "battery-low",
  "🪰": "fly",
  "🪱": "worm",
  "🪳": "cockroach",
  "🪼": "jellyfish",
  "🫀": "anatomical-heart",
  "🫏": "donkey",
  "🫠": "melting",
  "🫡": "salute",
  "🫢": "mouth-none",
  "🫣": "peeking",
  "🫤": "diagonal-mouth",
  "🫥": "dotted-line-face",
  "🫦": "biting-lip",
  "🫧": "bubbles",
  "🫨": "shaking-face",
  "😀": "grinning",
  "😁": "grin",
  "😂": "happy-cry",
  "😄": "smile-with-big-eyes",
  "😅": "grin-sweat",
  "😆": "laughing",
  "😇": "halo",
  "😈": "imp-smile",
  "😉": "wink",
  "😊": "blush",
  "😋": "yum",
  "😌": "relieved",
  "😍": "heart-eyes",
  "😎": "sunglasses-face",
  "😏": "smirk",
  "😐": "neutral-face",
  "😑": "expressionless",
  "😒": "unamused",
  "😓": "sweat",
  "😔": "pensive",
  "😖": "scrunched-eyes",
  "😗": "kissing",
  "😘": "kissing-heart",
  "😙": "kissing-smiling-eyes",
  "😚": "kissing-closed-eyes",
  "😛": "stuck-out-tongue",
  "😜": "squinting-tongue",
  "😟": "concerned",
  "😠": "angry",
  "😡": "rage",
  "😢": "cry",
  "😤": "triumph",
  "😧": "anguished",
  "😨": "scared",
  "😩": "weary",
  "😪": "sleepy",
  "😬": "grimacing",
  "😭": "distraught",
  "😮": "gasp",
  "😮‍💨": "exhale",
  "😰": "anxious-with-sweat",
  "😱": "screaming",
  "😲": "astonished",
  "😳": "flushed",
  "😴": "sleep",
  "😵": "dizzy-face",
  "😶‍🌫️": "face-in-clouds",
  "😷": "mask",
  "😸": "smile-cat",
  "😹": "joy-cat",
  "😺": "smiley-cat",
  "😻": "heart-eyes-cat",
  "😼": "smirk-cat",
  "😽": "kissing-cat",
  "😾": "pouting-cat",
  "😿": "crying-cat-face",
  "🙀": "scream-cat",
  "🙁": "slightly-frowning",
  "🙂": "slightly-happy",
  "🙃": "upside-down-face",
  "🙄": "rolling-eyes",
  "🙈": "see-no-evil-monkey",
  "🙉": "hear-no-evil-monkey",
  "🙊": "speak-no-evil-monkey",
  "🙌": "raising-hands",
  "🙏": "folded-hands",
  "🚀": "rocket",
  "🚨": "police-car-light",
  "🚩": "triangular-flag",
  "🚲": "bicycle",
  "🛎️": "bellhop-bell",
  "🛬": "airplane-arrival",
  "🛸": "flying-saucer",
  "🆓": "free",
  "🆕": "new",
  "🆘": "sos",
  "🆙": "up",
};

/**
 * 获取所有 emoji（平铺的列表）
 */
export function getAllEmojis(): Array<{
  emoji: string;
  name: string;
  category: string;
}> {
  return Object.entries(EMOJI_TO_CARTOON_MAP).map(([emoji, cartoonName]) => {
    const category = Object.keys(EMOJI_CATEGORIES).find((cat) =>
      EMOJI_CATEGORIES[cat].emojis.includes(emoji),
    );
    return { emoji, name: cartoonName, category: category || "objects" };
  });
}

/**
 * 搜索 emoji
 * @param term 搜索关键词
 * @returns 匹配的 emoji 列表
 */
export function searchEmojis(term: string): Array<{
  emoji: string;
  name: string;
  category: string;
}> {
  const termLower = term.toLowerCase();

  // 获取所有 emoji 的平铺列表
  const allEmojis = getAllEmojis();

  // 过滤出匹配的 emoji
  const results = allEmojis.filter((item) => {
    // 检查是否是直接的 emoji 匹配
    if (item.emoji === term) {
      return true;
    }

    // 检查分类名称
    if (item.category.toLowerCase().includes(termLower)) {
      return true;
    }

    // 检查映射表中的卡通版本名称
    const cartoonName = EMOJI_TO_CARTOON_MAP[item.emoji];
    if (cartoonName && cartoonName.toLowerCase().includes(termLower)) {
      return true;
    }

    return false;
  });

  return results;
}

/**
 * 将普通 emoji 转换为卡通版本对应的 name
 * 如果没有映射，返回原始 emoji
 * @param emoji - 普通 emoji 或卡通版本 name
 * @returns 卡通版本 name 或原始 emoji
 */
export function mapEmojiToCartoon(emoji: string): string {
  return EMOJI_TO_CARTOON_MAP[emoji] || emoji;
}

/**
 * 检查是否是有效的 emoji
 * @param emoji - 待检查的 emoji
 * @returns 如果是有效的 emoji，返回 true；否则返回 false
 */
export function isValidEmoji(emoji: string): boolean {
  return Object.keys(EMOJI_TO_CARTOON_MAP).includes(emoji);
}
