/**
 * Unified emoji animation configuration
 * 统一的emoji动画配置，包含video URL和对应的unicode字符
 * 避免在videoAnimations和emojiMap之间重复维护相同的emoji名称
 */

export interface EmojiConfig {
  name: string;
  videoFileName: string; // 相对文件名，会自动拼接BASE_URL
  unicode: string; // Unicode emoji字符
}

const BASE_URL = "https://storage.sciol.ac.cn/library/docs/public/";

// 统一的emoji配置列表
const EMOJI_CONFIGS: EmojiConfig[] = [
  { name: "100", videoFileName: "100-0.5x.webm", unicode: "💯" },
  {
    name: "airplane-arrival",
    videoFileName: "airplane-arrival-0.5x.webm",
    unicode: "🛬",
  },
  {
    name: "airplane-departure",
    videoFileName: "airplane-departure-2x.webm",
    unicode: "✈️",
  },
  { name: "alarm", videoFileName: "alarm-clock-1x.mp4", unicode: "⏰" },
  { name: "alien", videoFileName: "alien-0.5x.webm", unicode: "👽" },
  {
    name: "anatomical-heart",
    videoFileName: "anatomical-heart-0.5x.webm",
    unicode: "🫀",
  },
  { name: "angry", videoFileName: "angry-0.5x.webm", unicode: "😠" },
  { name: "anguished", videoFileName: "anguished-0.5x.webm", unicode: "😧" },
  { name: "ant", videoFileName: "ant-0.5x.webm", unicode: "🐜" },
  {
    name: "anxious-with-sweat",
    videoFileName: "anxious-with-sweat-0.5x.webm",
    unicode: "😰",
  },
  { name: "aquarius", videoFileName: "aquarius-0.5x.webm", unicode: "♒️" },
  { name: "aries", videoFileName: "aries-0.5x.webm", unicode: "♈️" },
  {
    name: "arm-mechanical",
    videoFileName: "arm-mechanical-0.5x.webm",
    unicode: "🦾",
  },
  { name: "astonished", videoFileName: "astonished-0.5x.webm", unicode: "😲" },
  { name: "baby-chick", videoFileName: "baby-chick-0.5x.webm", unicode: "🐤" },
  { name: "badminton", videoFileName: "badminton-0.5x.webm", unicode: "🏸" },
  {
    name: "balance-scale",
    videoFileName: "balance-scale-0.5x.webm",
    unicode: "⚖️",
  },
  { name: "balloon", videoFileName: "balloon-0.5x.webm", unicode: "🎈" },
  {
    name: "bandage-face",
    videoFileName: "bandage-face-0.5x.webm",
    unicode: "🤕",
  },
  {
    name: "bandaged-heart",
    videoFileName: "bandaged-heart-0.5x.webm",
    unicode: "💔",
  },
  { name: "baseball", videoFileName: "baseball-0.5x.webm", unicode: "⚾" },
  { name: "bat", videoFileName: "bat-0.5x.webm", unicode: "🦇" },
  {
    name: "battery-full",
    videoFileName: "battery-full-0.5x.webm",
    unicode: "🔋",
  },
  {
    name: "battery-low",
    videoFileName: "battery-low-0.5x.webm",
    unicode: "🪫",
  },
  {
    name: "beating-heart",
    videoFileName: "beating-heart-0.5x.webm",
    unicode: "💓",
  },
  { name: "bee", videoFileName: "bee-0.5x.webm", unicode: "🐝" },
  { name: "bell", videoFileName: "bell-0.5x.webm", unicode: "🔔" },
  {
    name: "bellhop-bell",
    videoFileName: "bellhop-bell-0.5x.webm",
    unicode: "🛎️",
  },
  { name: "bicycle", videoFileName: "bicycle-0.5x.webm", unicode: "🚲" },
  { name: "big-frown", videoFileName: "big-frown-0.5x.webm", unicode: "☹️" },
  { name: "bird", videoFileName: "bird-0.5x.webm", unicode: "🐦" },
  {
    name: "birthday-cake",
    videoFileName: "birthday-cake-0.5x.webm",
    unicode: "🎂",
  },
  { name: "biting-lip", videoFileName: "biting-lip-0.5x.webm", unicode: "🫦" },
  { name: "black-bird", videoFileName: "black-bird-0.5x.webm", unicode: "🐦‍⬛" },
  { name: "black-flag", videoFileName: "black-flag-0.5x.webm", unicode: "🏴" },
  {
    name: "black-heart",
    videoFileName: "black-heart-0.5x.webm",
    unicode: "🖤",
  },
  { name: "blood", videoFileName: "blood-0.5x.webm", unicode: "🩸" },
  { name: "blowfish", videoFileName: "blowfish-0.5x.webm", unicode: "🐡" },
  { name: "blue-heart", videoFileName: "blue-heart-0.5x.webm", unicode: "💙" },
  { name: "blush", videoFileName: "blush-0.5x.webm", unicode: "😊" },
  { name: "boomerang", videoFileName: "boomerang-0.5x.webm", unicode: "🪃" },
  {
    name: "bottle-with-popping-cork",
    videoFileName: "bottle-with-popping-cork-0.5x.webm",
    unicode: "🍾",
  },
  { name: "bowling", videoFileName: "bowling-0.5x.webm", unicode: "🎳" },
  {
    name: "broken-heart",
    videoFileName: "broken-heart-0.5x.webm",
    unicode: "💔",
  },
  {
    name: "brown-heart",
    videoFileName: "brown-heart-0.5x.webm",
    unicode: "🤎",
  },
  { name: "bubbles", videoFileName: "bubbles-0.5x.webm", unicode: "🫧" },
  { name: "bug", videoFileName: "bug-0.5x.webm", unicode: "🐛" },
  { name: "butterfly", videoFileName: "butterfly-0.5x.webm", unicode: "🦋" },
  {
    name: "camera-flash",
    videoFileName: "camera-flash-0.5x.webm",
    unicode: "📸",
  },
  { name: "camping", videoFileName: "camping-0.5x.webm", unicode: "🏕️" },
  { name: "cancer", videoFileName: "cancer-0.5x.webm", unicode: "♋️" },
  { name: "capricorn", videoFileName: "capricorn-0.5x.webm", unicode: "♑️" },
  { name: "check-mark", videoFileName: "check-mark-0.5x.webm", unicode: "✅" },
  {
    name: "chequered-flag",
    videoFileName: "chequered-flag-0.5x.webm",
    unicode: "🏁",
  },
  { name: "chipmunk", videoFileName: "chipmunk-0.5x.webm", unicode: "🐿️" },
  { name: "clap", videoFileName: "clap-0.5x.webm", unicode: "👏" },
  {
    name: "clinking-beer-mugs",
    videoFileName: "clinking-beer-mugs-0.5x.webm",
    unicode: "🍻",
  },
  {
    name: "clinking-glasses",
    videoFileName: "clinking-glasses-0.5x.webm",
    unicode: "🥂",
  },
  {
    name: "cloud-with-lightning",
    videoFileName: "cloud-with-lightning-0.5x.webm",
    unicode: "⛈️",
  },
  { name: "clown", videoFileName: "clown-0.5x.webm", unicode: "🤡" },
  { name: "cockroach", videoFileName: "cockroach-0.5x.webm", unicode: "🪳" },
  { name: "cold-face", videoFileName: "cold-face-0.5x.webm", unicode: "🥶" },
  { name: "collision", videoFileName: "collision-0.5x.webm", unicode: "💥" },
  { name: "comet", videoFileName: "comet-0.5x.webm", unicode: "☄️" },
  { name: "concerned", videoFileName: "concerned-0.5x.webm", unicode: "😟" },
  {
    name: "confetti-ball",
    videoFileName: "confetti-ball-0.5x.webm",
    unicode: "🎉",
  },
  {
    name: "construction",
    videoFileName: "construction-0.5x.webm",
    unicode: "🏗️",
  },
  { name: "cooking", videoFileName: "cooking-0.5x.webm", unicode: "🍳" },
  { name: "cool", videoFileName: "cool-0.5x.webm", unicode: "😎" },
  { name: "cow-face", videoFileName: "cow-face-0.5x.webm", unicode: "🐄" },
  { name: "cowboy", videoFileName: "cowboy-0.5x.webm", unicode: "🤠" },
  { name: "crab", videoFileName: "crab-0.5x.webm", unicode: "🦀" },
  {
    name: "cricket-game",
    videoFileName: "cricket-game-0.5x.webm",
    unicode: "🏏",
  },
  { name: "crocodile", videoFileName: "crocodile-0.5x.webm", unicode: "🐊" },
  { name: "cross-mark", videoFileName: "cross-mark-0.5x.webm", unicode: "❌" },
  {
    name: "crossed-fingers",
    videoFileName: "crossed-fingers-0.5x.webm",
    unicode: "🤞",
  },
  {
    name: "crystal-ball",
    videoFileName: "crystal-ball-0.5x.webm",
    unicode: "🔮",
  },
  { name: "cupid", videoFileName: "cupid-0.5x.webm", unicode: "💘" },
  { name: "cursing", videoFileName: "cursing-0.5x.webm", unicode: "🤬" },
  {
    name: "dancer-woman",
    videoFileName: "dancer-woman-0.5x.webm",
    unicode: "💃",
  },
  {
    name: "diagonal-mouth",
    videoFileName: "diagonal-mouth-0.5x.webm",
    unicode: "🫤",
  },
  { name: "die", videoFileName: "die-0.5x.webm", unicode: "🎲" },
  { name: "dinosaur", videoFileName: "dinosaur-0.5x.webm", unicode: "🦕" },
  { name: "direct-hit", videoFileName: "direct-hit-0.5x.webm", unicode: "🎯" },
  { name: "disguise", videoFileName: "disguise-0.5x.webm", unicode: "🥸" },
  { name: "distraught", videoFileName: "distraught-0.5x.webm", unicode: "😭" },
  { name: "dizzy", videoFileName: "dizzy-0.5x.webm", unicode: "💫" },
  { name: "dizzy-face", videoFileName: "dizzy-face-0.5x.webm", unicode: "😵" },
  { name: "dog", videoFileName: "dog-0.5x.webm", unicode: "🐕" },
  { name: "dolphin", videoFileName: "dolphin-0.5x.webm", unicode: "🐬" },
  { name: "donkey", videoFileName: "donkey-0.5x.webm", unicode: "🫏" },
  {
    name: "dotted-line-face",
    videoFileName: "dotted-line-face-0.5x.webm",
    unicode: "🫥",
  },
  { name: "dragon", videoFileName: "dragon-0.5x.webm", unicode: "🐉" },
  { name: "drool", videoFileName: "drool-0.5x.webm", unicode: "🤤" },
  { name: "droplet", videoFileName: "droplet-0.5x.webm", unicode: "💧" },
  { name: "drum", videoFileName: "drum-0.5x.webm", unicode: "🥁" },
  { name: "eagle", videoFileName: "eagle-0.5x.webm", unicode: "🦅" },
  {
    name: "electricity",
    videoFileName: "electricity-0.5x.webm",
    unicode: "⚡",
  },
  {
    name: "exclamation",
    videoFileName: "exclamation-0.5x.webm",
    unicode: "❗",
  },
  {
    name: "exclamation-double",
    videoFileName: "exclamation-double-0.5x.webm",
    unicode: "‼️",
  },
  {
    name: "exclamation-question-mark",
    videoFileName: "exclamation-question-mark-0.5x.webm",
    unicode: "⁉️",
  },
  { name: "exhale", videoFileName: "exhale-0.5x.webm", unicode: "😮‍💨" },
  {
    name: "expressionless",
    videoFileName: "expressionless-0.5x.webm",
    unicode: "😑",
  },
  { name: "eye", videoFileName: "eye-0.5x.webm", unicode: "👁️" },
  { name: "eyes", videoFileName: "eyes-0.5x.webm", unicode: "👀" },
  {
    name: "face-in-clouds",
    videoFileName: "face-in-clouds-0.5x.webm",
    unicode: "😶‍🌫️",
  },
  {
    name: "fallen-leaf",
    videoFileName: "fallen-leaf-0.5x.webm",
    unicode: "🍂",
  },
  {
    name: "field-hockey",
    videoFileName: "field-hockey-0.5x.webm",
    unicode: "🏑",
  },
  { name: "fire", videoFileName: "fire-0.5x.webm", unicode: "🔥" },
  { name: "fire-heart", videoFileName: "fire-heart-0.5x.webm", unicode: "❤️‍🔥" },
  { name: "fireworks", videoFileName: "fireworks-0.5x.webm", unicode: "🎆" },
  { name: "flushed", videoFileName: "flushed-0.5x.webm", unicode: "😳" },
  { name: "fly", videoFileName: "fly-0.5x.webm", unicode: "🪰" },
  {
    name: "flying-disc",
    videoFileName: "flying-disc-0.5x.webm",
    unicode: "🥏",
  },
  {
    name: "flying-saucer",
    videoFileName: "flying-saucer-0.5x.webm",
    unicode: "🛸",
  },
  {
    name: "folded-hands",
    videoFileName: "folded-hands-0.5x.webm",
    unicode: "🙏",
  },
  { name: "footprints", videoFileName: "footprints-0.5x.webm", unicode: "👣" },
  { name: "free", videoFileName: "free-0.5x.webm", unicode: "🆓" },
  { name: "frog", videoFileName: "frog-0.5x.webm", unicode: "🐸" },
  { name: "gasp", videoFileName: "gasp-0.5x.webm", unicode: "😮" },
  { name: "gear", videoFileName: "gear-0.5x.webm", unicode: "⚙️" },
  { name: "gem-stone", videoFileName: "gem-stone-0.5x.webm", unicode: "💎" },
  { name: "gemini", videoFileName: "gemini-0.5x.webm", unicode: "♊️" },
  { name: "ghost", videoFileName: "ghost-0.5x.webm", unicode: "👻" },
  { name: "gift-heart", videoFileName: "gift-heart-0.5x.webm", unicode: "💝" },
  {
    name: "globe-showing-americas",
    videoFileName: "globe-showing-americas-0.5x.webm",
    unicode: "🌎",
  },
  {
    name: "globe-showing-asia-australia",
    videoFileName: "globe-showing-asia-australia-0.5x.webm",
    unicode: "🌏",
  },
  {
    name: "globe-showing-europe-africa",
    videoFileName: "globe-showing-europe-africa-0.5x.webm",
    unicode: "🌍",
  },
  {
    name: "glowing-star",
    videoFileName: "glowing-star-0.5x.webm",
    unicode: "🌟",
  },
  { name: "goat", videoFileName: "goat-0.5x.webm", unicode: "🐐" },
  { name: "goose", videoFileName: "goose-0.5x.webm", unicode: "🦆" },
  { name: "gorilla", videoFileName: "gorilla-0.5x.webm", unicode: "🦍" },
  {
    name: "graduation-cap",
    videoFileName: "graduation-cap-0.5x.webm",
    unicode: "🎓",
  },
  {
    name: "green-heart",
    videoFileName: "green-heart-0.5x.webm",
    unicode: "💚",
  },
  { name: "grey-heart", videoFileName: "grey-heart-0.5x.webm", unicode: "🩶" },
  { name: "grimacing", videoFileName: "grimacing-0.5x.webm", unicode: "😬" },
  { name: "grin", videoFileName: "grin-0.5x.webm", unicode: "😁" },
  { name: "grin-sweat", videoFileName: "grin-sweat-0.5x.webm", unicode: "😅" },
  { name: "grinning", videoFileName: "grinning-0.5x.webm", unicode: "😀" },
  { name: "guide-dog", videoFileName: "guide-dog-0.5x.webm", unicode: "🦮" },
  { name: "halo", videoFileName: "halo-0.5x.webm", unicode: "😇" },
  {
    name: "hand-over-mouth",
    videoFileName: "hand-over-mouth-0.5x.webm",
    unicode: "🤭",
  },
  { name: "happy-cry", videoFileName: "happy-cry-0.5x.webm", unicode: "😂" },
  {
    name: "hatched-chick",
    videoFileName: "hatched-chick-0.5x.webm",
    unicode: "🐥",
  },
  {
    name: "hatching-chick",
    videoFileName: "hatching-chick-0.5x.webm",
    unicode: "🐣",
  },
  {
    name: "hear-no-evil-monkey",
    videoFileName: "hear-no-evil-monkey-0.5x.webm",
    unicode: "🙉",
  },
  {
    name: "heart-exclamation-point",
    videoFileName: "heart-exclamation-point-0.5x.webm",
    unicode: "❣️",
  },
  { name: "heart-eyes", videoFileName: "heart-eyes-0.5x.webm", unicode: "😍" },
  {
    name: "heart-eyes-cat",
    videoFileName: "heart-eyes-cat-0.5x.webm",
    unicode: "😻",
  },
  { name: "heart-face", videoFileName: "heart-face-0.5x.webm", unicode: "🥰" },
  { name: "heart-grow", videoFileName: "heart-grow-0.5x.webm", unicode: "💗" },
  {
    name: "holding-back-tears",
    videoFileName: "holding-back-tears-0.5x.webm",
    unicode: "🥹",
  },
  {
    name: "hot-beverage",
    videoFileName: "hot-beverage-0.5x.webm",
    unicode: "☕",
  },
  { name: "hot-face", videoFileName: "hot-face-0.5x.webm", unicode: "🥵" },
  { name: "hug-face", videoFileName: "hug-face-0.5x.webm", unicode: "🤗" },
  { name: "ice-hockey", videoFileName: "ice-hockey-0.5x.webm", unicode: "🏒" },
  { name: "imp-frown", videoFileName: "imp-frown-0.5x.webm", unicode: "👿" },
  { name: "imp-smile", videoFileName: "imp-smile-0.5x.webm", unicode: "😈" },
  {
    name: "index-finger",
    videoFileName: "index-finger-0.5x.webm",
    unicode: "☝️",
  },
  {
    name: "jack-o-lantern",
    videoFileName: "jack-o-lantern-0.5x.webm",
    unicode: "🎃",
  },
  { name: "jellyfish", videoFileName: "jellyfish-0.5x.webm", unicode: "🪼" },
  { name: "joy-cat", videoFileName: "joy-cat-0.5x.webm", unicode: "😹" },
  { name: "kangaroo", videoFileName: "kangaroo-0.5x.webm", unicode: "🦘" },
  { name: "kiss", videoFileName: "kiss-0.5x.webm", unicode: "💋" },
  { name: "kissing", videoFileName: "kissing-0.5x.webm", unicode: "😗" },
  {
    name: "kissing-cat",
    videoFileName: "kissing-cat-0.5x.webm",
    unicode: "😽",
  },
  {
    name: "kissing-closed-eyes",
    videoFileName: "kissing-closed-eyes-0.5x.webm",
    unicode: "😚",
  },
  {
    name: "kissing-heart",
    videoFileName: "kissing-heart-0.5x.webm",
    unicode: "😘",
  },
  {
    name: "kissing-smiling-eyes",
    videoFileName: "kissing-smiling-eyes-0.5x.webm",
    unicode: "😙",
  },
  { name: "kite", videoFileName: "kite-0.5x.webm", unicode: "🪁" },
  { name: "lacrosse", videoFileName: "lacrosse-0.5x.webm", unicode: "🥌" },
  { name: "lady-bug", videoFileName: "lady-bug-0.5x.webm", unicode: "🐞" },
  { name: "laughing", videoFileName: "laughing-0.5x.webm", unicode: "😆" },
  { name: "leaves", videoFileName: "leaves-0.5x.webm", unicode: "🍃" },
  {
    name: "leg-mechanical",
    videoFileName: "leg-mechanical-0.5x.webm",
    unicode: "🦿",
  },
  { name: "leo", videoFileName: "leo-0.5x.webm", unicode: "♌️" },
  { name: "liar", videoFileName: "liar-0.5x.webm", unicode: "🤥" },
  { name: "libra", videoFileName: "libra-0.5x.webm", unicode: "♎️" },
  {
    name: "light-blue-heart",
    videoFileName: "light-blue-heart-0.5x.webm",
    unicode: "🩵",
  },
  { name: "light-bulb", videoFileName: "light-bulb-0.5x.webm", unicode: "💡" },
  { name: "litter", videoFileName: "litter-0.5x.webm", unicode: "🗑️" },
  { name: "lizard", videoFileName: "lizard-0.5x.webm", unicode: "🦎" },
  {
    name: "love-letter",
    videoFileName: "love-letter-0.5x.webm",
    unicode: "💌",
  },
  { name: "luck", videoFileName: "luck-0.5x.webm", unicode: "🍀" },
  { name: "maracas", videoFileName: "maracas-0.5x.webm", unicode: "🪇" },
  { name: "mask", videoFileName: "mask-0.5x.webm", unicode: "😷" },
  { name: "melting", videoFileName: "melting-0.5x.webm", unicode: "🫠" },
  { name: "microbe", videoFileName: "microbe-0.5x.webm", unicode: "🦠" },
  { name: "mind-blown", videoFileName: "mind-blown-0.5x.webm", unicode: "🤯" },
  {
    name: "mirror-ball",
    videoFileName: "mirror-ball-0.5x.webm",
    unicode: "🪩",
  },
  { name: "money-face", videoFileName: "money-face-0.5x.webm", unicode: "🤑" },
  {
    name: "money-with-wings",
    videoFileName: "money-with-wings-0.5x.webm",
    unicode: "💸",
  },
  { name: "monkey", videoFileName: "monkey-0.5x.webm", unicode: "🐵" },
  { name: "monocle", videoFileName: "monocle-0.5x.webm", unicode: "🧐" },
  {
    name: "moon-face-first-quarter",
    videoFileName: "moon-face-first-quarter-0.5x.webm",
    unicode: "🌓",
  },
  {
    name: "moon-face-last-quarter",
    videoFileName: "moon-face-last-quarter-0.5x.webm",
    unicode: "🌗",
  },
  { name: "mosquito", videoFileName: "mosquito-0.5x.webm", unicode: "🦟" },
  { name: "mouth-none", videoFileName: "mouth-none-1x.webm", unicode: "🫢" },
  { name: "muscle", videoFileName: "muscle-0.5x.webm", unicode: "💪" },
  {
    name: "musical-notes",
    videoFileName: "musical-notes-0.5x.webm",
    unicode: "🎵",
  },
  { name: "nerd-face", videoFileName: "nerd-face-0.5x.webm", unicode: "🤓" },
  {
    name: "neutral-face",
    videoFileName: "neutral-face-0.5x.webm",
    unicode: "😐",
  },
  { name: "new", videoFileName: "new-0.5x.webm", unicode: "🆕" },
  { name: "ocean", videoFileName: "ocean-0.5x.webm", unicode: "🌊" },
  { name: "octopus", videoFileName: "octopus-0.5x.webm", unicode: "🐙" },
  { name: "ophiuchus", videoFileName: "ophiuchus-0.5x.webm", unicode: "⛎" },
  {
    name: "orange-heart",
    videoFileName: "orange-heart-0.5x.webm",
    unicode: "🧡",
  },
  { name: "orangutan", videoFileName: "orangutan-0.5x.webm", unicode: "🦧" },
  { name: "otter", videoFileName: "otter-0.5x.webm", unicode: "🦦" },
  { name: "ox", videoFileName: "ox-0.5x.webm", unicode: "🐂" },
  {
    name: "partying-face",
    videoFileName: "partying-face-0.5x.webm",
    unicode: "🥳",
  },
  { name: "paw-prints", videoFileName: "paw-prints-0.5x.webm", unicode: "🐾" },
  { name: "peace", videoFileName: "peace-0.5x.webm", unicode: "☮️" },
  { name: "peacock", videoFileName: "peacock-0.5x.webm", unicode: "🦚" },
  { name: "peeking", videoFileName: "peeking-0.5x.webm", unicode: "🫣" },
  { name: "pencil", videoFileName: "pencil-0.5x.webm", unicode: "✏️" },
  { name: "pensive", videoFileName: "pensive-0.5x.mp4", unicode: "😔" },
  { name: "phone-off", videoFileName: "phone-off-0.5x.webm", unicode: "📴" },
  { name: "pig", videoFileName: "pig-0.5x.webm", unicode: "🐷" },
  { name: "pinata", videoFileName: "pinata-0.5x.webm", unicode: "🪅" },
  { name: "ping-pong", videoFileName: "ping-pong-0.5x.webm", unicode: "🏓" },
  { name: "pink-heart", videoFileName: "pink-heart-0.5x.webm", unicode: "🩷" },
  { name: "pisces", videoFileName: "pisces-0.5x.webm", unicode: "♓️" },
  { name: "plant", videoFileName: "plant-0.5x.webm", unicode: "🌱" },
  { name: "pleading", videoFileName: "pleading-0.5x.webm", unicode: "🥺" },
  { name: "plus-sign", videoFileName: "plus-sign-0.5x.webm", unicode: "➕" },
  {
    name: "police-car-light",
    videoFileName: "police-car-light-0.5x.webm",
    unicode: "🚨",
  },
  { name: "poodle", videoFileName: "poodle-0.5x.webm", unicode: "🐩" },
  { name: "poop", videoFileName: "poop-0.5x.webm", unicode: "💩" },
  { name: "popcorn", videoFileName: "popcorn-0.5x.webm", unicode: "🍿" },
  {
    name: "pouting-cat",
    videoFileName: "pouting-cat-0.5x.webm",
    unicode: "😾",
  },
  {
    name: "purple-heart",
    videoFileName: "purple-heart-0.5x.webm",
    unicode: "💜",
  },
  { name: "question", videoFileName: "question-0.5x.webm", unicode: "❓" },
  { name: "rabbit", videoFileName: "rabbit-0.5x.webm", unicode: "🐰" },
  { name: "racehorse", videoFileName: "racehorse-0.5x.webm", unicode: "🐎" },
  { name: "rage", videoFileName: "rage-0.5x.webm", unicode: "😡" },
  { name: "rainbow", videoFileName: "rainbow-0.5x.webm", unicode: "🌈" },
  { name: "rain-cloud", videoFileName: "rain-cloud-0.5x.webm", unicode: "🌧️" },
  {
    name: "raised-eyebrow",
    videoFileName: "raised-eyebrow-0.5x.webm",
    unicode: "🤨",
  },
  {
    name: "raising-hands",
    videoFileName: "raising-hands-0.5x.webm",
    unicode: "🙌",
  },
  { name: "rat", videoFileName: "rat-0.5x.webm", unicode: "🐀" },
  { name: "red-heart", videoFileName: "red-heart-0.5x.webm", unicode: "❤️" },
  { name: "relieved", videoFileName: "relieved-0.5x.webm", unicode: "😌" },
  {
    name: "revolving-hearts",
    videoFileName: "revolving-hearts-0.5x.webm",
    unicode: "💞",
  },
  { name: "robot", videoFileName: "robot-0.5x.webm", unicode: "🤖" },
  { name: "rocket", videoFileName: "rocket-0.5x.webm", unicode: "🚀" },
  { name: "rofl", videoFileName: "rofl-0.5x.webm", unicode: "🤣" },
  {
    name: "roller-coaster",
    videoFileName: "roller-coaster-0.5x.webm",
    unicode: "🎢",
  },
  {
    name: "rolling-eyes",
    videoFileName: "rolling-eyes-0.5x.webm",
    unicode: "🙄",
  },
  { name: "rooster", videoFileName: "rooster-0.5x.webm", unicode: "🐓" },
  { name: "rose", videoFileName: "rose-0.5x.webm", unicode: "🌹" },
  {
    name: "sagittarius",
    videoFileName: "sagittarius-0.5x.webm",
    unicode: "♐️",
  },
  { name: "salute", videoFileName: "salute-0.5x.webm", unicode: "🫡" },
  { name: "scared", videoFileName: "scared-0.5x.webm", unicode: "😨" },
  { name: "scorpio", videoFileName: "scorpio-0.5x.webm", unicode: "♏️" },
  { name: "scream-cat", videoFileName: "scream-cat-0.5x.webm", unicode: "🙀" },
  { name: "screaming", videoFileName: "screaming-0.5x.webm", unicode: "😱" },
  {
    name: "scrunched-eyes",
    videoFileName: "scrunched-eyes-0.5x.mp4",
    unicode: "😖",
  },
  {
    name: "scrunched-mouth",
    videoFileName: "scrunched-mouth-0.5x.webm",
    unicode: "🤐",
  },
  { name: "seal", videoFileName: "seal-0.5x.webm", unicode: "🦭" },
  {
    name: "see-no-evil-monkey",
    videoFileName: "see-no-evil-monkey-0.5x.webm",
    unicode: "🙈",
  },
  {
    name: "shaking-face",
    videoFileName: "shaking-face-0.5x.webm",
    unicode: "🫨",
  },
  { name: "shark", videoFileName: "shark-0.5x.webm", unicode: "🦈" },
  {
    name: "shushing-face",
    videoFileName: "shushing-face-0.5x.webm",
    unicode: "🤫",
  },
  { name: "sick", videoFileName: "sick-0.5x.webm", unicode: "🤒" },
  { name: "skull", videoFileName: "skull-0.5x.webm", unicode: "💀" },
  { name: "sleep", videoFileName: "sleep-0.5x.webm", unicode: "😴" },
  { name: "sleepy", videoFileName: "sleepy-0.5x.webm", unicode: "😪" },
  {
    name: "slightly-frowning",
    videoFileName: "slightly-frowning-0.5x.webm",
    unicode: "🙁",
  },
  {
    name: "slightly-happy",
    videoFileName: "slightly-happy-0.5x.webm",
    unicode: "🙂",
  },
  {
    name: "slot-machine",
    videoFileName: "slot-machine-0.5x.webm",
    unicode: "🎰",
  },
  { name: "smile-cat", videoFileName: "smile-cat-0.5x.webm", unicode: "😸" },
  {
    name: "smile-with-big-eyes",
    videoFileName: "smile-with-big-eyes-0.5x.webm",
    unicode: "😄",
  },
  { name: "smiley-cat", videoFileName: "smiley-cat-0.5x.webm", unicode: "😺" },
  { name: "smirk", videoFileName: "smirk-0.5x.webm", unicode: "😏" },
  { name: "smirk-cat", videoFileName: "smirk-cat-0.5x.webm", unicode: "😼" },
  { name: "snail", videoFileName: "snail-0.5x.webm", unicode: "🐌" },
  { name: "snake", videoFileName: "snake-0.5x.webm", unicode: "🐍" },
  { name: "sneeze", videoFileName: "sneeze-0.5x.webm", unicode: "🤧" },
  { name: "snowflake", videoFileName: "snowflake-0.5x.webm", unicode: "❄️" },
  {
    name: "soccer-ball",
    videoFileName: "soccer-ball-0.5x.webm",
    unicode: "⚽",
  },
  { name: "softball", videoFileName: "softball-0.5x.webm", unicode: "🥎" },
  { name: "sos", videoFileName: "sos-0.5x.webm", unicode: "🆘" },
  { name: "spaghetti", videoFileName: "spaghetti-0.5x.webm", unicode: "🍝" },
  { name: "sparkles", videoFileName: "sparkles-0.5x.webm", unicode: "✨" },
  {
    name: "sparkling-heart",
    videoFileName: "sparkling-heart-0.5x.webm",
    unicode: "💖",
  },
  {
    name: "speak-no-evil-monkey",
    videoFileName: "speak-no-evil-monkey-0.5x.webm",
    unicode: "🙊",
  },
  { name: "spider", videoFileName: "spider-0.5x.webm", unicode: "🕷️" },
  {
    name: "squinting-tongue",
    videoFileName: "squinting-tongue-0.5x.webm",
    unicode: "😜",
  },
  {
    name: "star-struck",
    videoFileName: "star-struck-0.5x.webm",
    unicode: "🤩",
  },
  {
    name: "steaming-bowl",
    videoFileName: "steaming-bowl-0.5x.webm",
    unicode: "🍜",
  },
  {
    name: "stuck-out-tongue",
    videoFileName: "stuck-out-tongue-0.5x.webm",
    unicode: "😛",
  },
  {
    name: "sun-with-face",
    videoFileName: "sun-with-face-0.5x.webm",
    unicode: "🌞",
  },
  {
    name: "sunglasses-face",
    videoFileName: "sunglasses-face-0.5x.webm",
    unicode: "😎",
  },
  { name: "sunrise", videoFileName: "sunrise-0.5x.webm", unicode: "🌅" },
  {
    name: "sunrise-over-mountains",
    videoFileName: "sunrise-over-mountains-0.5x.webm",
    unicode: "🌄",
  },
  { name: "sweat", videoFileName: "sweat-0.5x.webm", unicode: "😓" },
  { name: "t-rex", videoFileName: "t-rex-0.5x.webm", unicode: "🦖" },
  { name: "taurus", videoFileName: "taurus-0.5x.webm", unicode: "♉️" },
  { name: "tennis", videoFileName: "tennis-0.5x.webm", unicode: "🎾" },
  {
    name: "thinking-face",
    videoFileName: "thinking-face-0.5x.webm",
    unicode: "🤔",
  },
  {
    name: "thumbs-down",
    videoFileName: "thumbs-down-0.5x.webm",
    unicode: "👎",
  },
  { name: "thumbs-up", videoFileName: "thumbs-up-0.5x.webm", unicode: "👍" },
  { name: "tiger", videoFileName: "tiger-0.5x.webm", unicode: "🐯" },
  { name: "tomato", videoFileName: "tomato-0.5x.webm", unicode: "🍅" },
  { name: "tornado", videoFileName: "tornado-0.5x.webm", unicode: "🌪️" },
  {
    name: "triangular-flag",
    videoFileName: "triangular-flag-0.5x.webm",
    unicode: "🚩",
  },
  { name: "triumph", videoFileName: "triumph-0.5x.webm", unicode: "😤" },
  {
    name: "tropical-drink",
    videoFileName: "tropical-drink-0.5x.webm",
    unicode: "🍹",
  },
  { name: "turtle", videoFileName: "turtle-0.5x.webm", unicode: "🐢" },
  { name: "two-hearts", videoFileName: "two-hearts-0.5x.webm", unicode: "💕" },
  { name: "umbrella", videoFileName: "umbrella-0.5x.webm", unicode: "☔" },
  { name: "unamused", videoFileName: "unamused-0.5x.webm", unicode: "😒" },
  { name: "unicorn", videoFileName: "unicorn-0.5x.webm", unicode: "🦄" },
  { name: "up", videoFileName: "up-0.5x.webm", unicode: "🆙" },
  {
    name: "upside-down-face",
    videoFileName: "upside-down-face-0.5x.webm",
    unicode: "🙃",
  },
  { name: "victory", videoFileName: "victory-0.5x.webm", unicode: "✌️" },
  { name: "violin", videoFileName: "violin-0.5x.webm", unicode: "🎻" },
  { name: "virgo", videoFileName: "virgo-0.5x.webm", unicode: "♍️" },
  { name: "volcano", videoFileName: "volcano-0.5x.webm", unicode: "🌋" },
  { name: "vomit", videoFileName: "vomit-0.5x.webm", unicode: "🤮" },
  { name: "wave", videoFileName: "wave-0.5x.webm", unicode: "👋" },
  { name: "weary", videoFileName: "weary-0.5x.webm", unicode: "😩" },
  { name: "whale", videoFileName: "whale-0.5x.webm", unicode: "🐋" },
  { name: "white-flag", videoFileName: "white-flag-0.5x.webm", unicode: "🏳️" },
  {
    name: "white-heart",
    videoFileName: "white-heart-0.5x.webm",
    unicode: "🤍",
  },
  {
    name: "wilted-flower",
    videoFileName: "wilted-flower-0.5x.webm",
    unicode: "🥀",
  },
  { name: "wind-face", videoFileName: "wind-face-0.5x.webm", unicode: "🌬️" },
  { name: "wine-glass", videoFileName: "wine-glass-0.5x.webm", unicode: "🍷" },
  { name: "wink", videoFileName: "wink-0.5x.webm", unicode: "😉" },
  { name: "woozy", videoFileName: "woozy-0.5x.webm", unicode: "🥴" },
  { name: "worm", videoFileName: "worm-0.5x.webm", unicode: "🪱" },
  {
    name: "wrapped-gift",
    videoFileName: "wrapped-gift-0.5x.webm",
    unicode: "🎁",
  },
  { name: "yawn", videoFileName: "yawn-0.5x.webm", unicode: "🥱" },
  {
    name: "yellow-heart",
    videoFileName: "yellow-heart-0.5x.webm",
    unicode: "💛",
  },
  { name: "yum", videoFileName: "yum-0.5x.webm", unicode: "😋" },
  { name: "zany-face", videoFileName: "zany-face-0.5x.webm", unicode: "🤪" },
  { name: "zipper-face", videoFileName: "zipper-face-1x.webm", unicode: "🤐" },
];

/**
 * Get a map of all available video animations.
 *
 * @returns A map where keys are animation names (e.g., "smirk")
 * and values are the video URLs.
 */
export const getVideoAnimationsMap = (): Record<string, string> => {
  const animationMap: Record<string, string> = {};
  EMOJI_CONFIGS.forEach((config) => {
    animationMap[config.name] = `${BASE_URL}${config.videoFileName}`;
  });
  return animationMap;
};

/**
 * Get a map of emojis to their fallback animation names.
 * This is used when a direct video for the emoji is not available.
 *
 * @returns A map where keys are emojis (e.g., "😊") and values are
 * animation names (e.g., "blush").
 */
export const getEmojiMap = (): Record<string, string> => {
  const emojiMap: Record<string, string> = {};
  EMOJI_CONFIGS.forEach((config) => {
    if (config.unicode) {
      emojiMap[config.unicode] = config.name;
    }
  });
  return emojiMap;
};

export default EMOJI_CONFIGS;
