"""
System Agent Manager

Manages per-user default agents (e.g. "小二") and the root CEO agent.
"""

import logging
from typing import TypedDict

from sqlmodel.ext.asyncio.session import AsyncSession

from app.models.agent import Agent, AgentCreate, AgentScope, ConfigVisibility
from app.repos.agent import AgentRepository
from app.repos.provider import ProviderRepository
from app.repos.root_agent import RootAgentRepository

logger = logging.getLogger(__name__)


class AgentConfig(TypedDict):
    name: str
    description: str
    prompt: str
    personality: str
    capabilities: list[str]
    avatar: str
    tags: list[str]


# Default agent configurations — each user gets a USER-scoped copy tagged "default_{key}"
SYSTEM_AGENTS: dict[str, AgentConfig] = {
    "chat": {
        "name": "小二",
        "description": "什么都能做，但什么都不专精",
        "prompt": """你是一个友好、有用的AI助手。你可以回答问题、提供建议、协助完成各种任务。

特点：
- 保持对话自然流畅，积极主动地帮助用户
- 可以使用各种工具来提供更好的帮助
- 对用户的问题给出准确、有用的回答
- 在不确定时会诚实地说明，并尝试提供替代方案

你的目标是成为用户最可靠的AI助手，帮助他们解决问题并提供有价值的信息。""",
        "personality": "friendly_assistant",
        "capabilities": ["general_chat", "qa", "assistance", "tools"],
        "avatar": "https://api.dicebear.com/7.x/avataaars/svg?seed=default",
        "tags": ["助手", "对话", "工具", "帮助"],
    },
}


class SystemAgentManager:
    """
    Manager for per-user default agents and the root (CEO) agent.
    """

    def __init__(self, db: AsyncSession):
        self.db = db
        self.agent_repo = AgentRepository(db)
        self.provider_repo = ProviderRepository(db)
        self.root_agent_repo = RootAgentRepository(db)

    async def ensure_user_default_agents(self, user_id: str) -> list[Agent]:
        """
        Check and ensure user has all default agents by verifying tags.
        If a specific default agent is missing, it will be recreated.

        Args:
            user_id: The ID of the user to initialize defaults for.

        Returns:
            List of newly created default agents for the user.
        """
        # Ensure root agent exists FIRST so parent_id defaults work
        await self.ensure_root_agent(user_id)

        # Fetch existing agents for the user to check tags
        existing_agents = await self.agent_repo.get_agents_by_user(user_id)
        existing_tags = set()
        for agent in existing_agents:
            if agent.tags:
                existing_tags.update(agent.tags)

        logger.info(f"Checking default agents for user: {user_id}")

        # Get system provider to set as default if available
        system_provider = await self.provider_repo.get_system_provider()

        created_agents = []
        for agent_key, config in SYSTEM_AGENTS.items():
            tag = f"default_{agent_key}"
            if tag in existing_tags:
                continue

            # Double check: Check if agent exists by name for this user
            # This helps prevent race conditions where multiple requests might try to create it
            existing_by_name = await self.agent_repo.get_agent_by_user_and_name(user_id, config["name"])

            if existing_by_name:
                # If agent exists but tag is missing, we might want to add the tag
                # For now, just logging and skipping to avoid duplication
                logger.info(
                    f"Agent '{config['name']}' exists for user {user_id} but missing tag {tag}. Skipping creation."
                )
                continue

            # Add a tag to identify which default agent this is
            tags = config.get("tags", [])
            if tag not in tags:
                tags = tags + [tag]

            # Note: graph_config will be auto-generated by AgentRepository.create_agent()
            # using ReActAgent.export_graph_config() - single source of truth

            agent_data = AgentCreate(
                scope=AgentScope.USER,
                name=config["name"],
                description=config["description"],
                prompt=config["prompt"],
                avatar=config.get("avatar"),
                tags=tags,
                provider_id=system_provider.id if system_provider else None,
                mcp_server_ids=[],  # Defaults start clean
                require_tool_confirmation=False,
                model=None,
                temperature=0.7,
                # graph_config=None - let repository generate it
            )

            agent = await self.agent_repo.create_agent(agent_data, user_id)
            created_agents.append(agent)
            logger.info(f"Created default {agent_key} agent for user {user_id}: {agent.id}")

        return created_agents

    async def ensure_root_agent(self, user_id: str) -> Agent:
        """
        Ensure the user has exactly one root (CEO) agent.
        If missing, creates the Agent record and links it in the root_agent table.
        """
        existing = await self.root_agent_repo.get_agent_for_user(user_id)
        if existing:
            return existing

        from app.agents.builtin import get_builtin_config

        ceo_config = get_builtin_config("ceo")
        system_provider = await self.provider_repo.get_system_provider()

        agent_data = AgentCreate(
            scope=AgentScope.USER,
            name="Xyzen",
            description="Your root agent that can orchestrate other agents",
            graph_config=ceo_config.model_dump() if ceo_config else None,
            config_visibility=ConfigVisibility.HIDDEN,
            config_editable=False,
            tags=["root_agent", "ceo"],
            provider_id=system_provider.id if system_provider else None,
            require_tool_confirmation=False,
        )

        agent = await self.agent_repo.create_agent(agent_data, user_id)
        await self.root_agent_repo.create(user_id=user_id, agent_id=agent.id)
        logger.info(f"Created root (CEO) agent for user {user_id}: {agent.id}")
        return agent


# Export constants for use in other modules
__all__ = [
    "SystemAgentManager",
    "SYSTEM_AGENTS",
]
