"""add sandbox_backend to sessions

Revision ID: 05df78067347
Revises: 2ff4ac5cb897
Create Date: 2026-03-02 16:25:32.463574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "05df78067347"
down_revision: Union[str, Sequence[str], None] = "2ff4ac5cb897"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("sandbox_backend", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "sandbox_backend")
    # ### end Alembic commands ###
