"""add beta_surveys and internal_applications tables

Revision ID: 0d658196ed81
Revises: eb1a03995023
Create Date: 2026-03-06 11:16:47.157373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0d658196ed81"
down_revision: Union[str, Sequence[str], None] = "eb1a03995023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beta_surveys",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("discovery_channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("occupation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("problem_to_solve", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_beta_surveys_id"), "beta_surveys", ["id"], unique=False)
    op.create_index(op.f("ix_beta_surveys_user_id"), "beta_surveys", ["user_id"], unique=False)
    op.create_table(
        "internal_applications",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("real_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("application_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("serial_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("certificate_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index(op.f("ix_internal_applications_id"), "internal_applications", ["id"], unique=False)
    op.create_index(op.f("ix_internal_applications_user_id"), "internal_applications", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_internal_applications_user_id"), table_name="internal_applications")
    op.drop_index(op.f("ix_internal_applications_id"), table_name="internal_applications")
    op.drop_table("internal_applications")
    op.drop_index(op.f("ix_beta_surveys_user_id"), table_name="beta_surveys")
    op.drop_index(op.f("ix_beta_surveys_id"), table_name="beta_surveys")
    op.drop_table("beta_surveys")
    # ### end Alembic commands ###
