"""add max_terminals and max_deployments to subscription role

Revision ID: 17aacd78562f
Revises: 44c0b189254e
Create Date: 2026-02-27 16:14:17.344755

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "17aacd78562f"
down_revision: Union[str, Sequence[str], None] = "44c0b189254e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployments",
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("start_command", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_dir", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sandbox_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deployments_id"), "deployments", ["id"], unique=False)
    op.create_index(op.f("ix_deployments_session_id"), "deployments", ["session_id"], unique=False)
    op.create_index(op.f("ix_deployments_user_id"), "deployments", ["user_id"], unique=False)
    op.add_column("subscriptionrole", sa.Column("max_terminals", sa.Integer(), server_default="1", nullable=False))
    op.add_column("subscriptionrole", sa.Column("max_deployments", sa.Integer(), server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptionrole", "max_deployments")
    op.drop_column("subscriptionrole", "max_terminals")
    op.drop_index(op.f("ix_deployments_user_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_session_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_id"), table_name="deployments")
    op.drop_table("deployments")
    # ### end Alembic commands ###
