"""add subscription

Revision ID: 17c153d0d131
Revises: 60a95cc43cd7
Create Date: 2026-02-11 16:13:48.290833

"""

from datetime import datetime, timezone
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "17c153d0d131"
down_revision: Union[str, Sequence[str], None] = "60a95cc43cd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptionrole",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("storage_limit_bytes", sa.BigInteger(), nullable=False),
        sa.Column("max_file_count", sa.Integer(), nullable=False),
        sa.Column("max_file_upload_bytes", sa.BigInteger(), nullable=False),
        sa.Column("max_parallel_chats", sa.Integer(), nullable=False),
        sa.Column("max_sandboxes", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptionrole_id"), "subscriptionrole", ["id"], unique=False)
    op.create_index(op.f("ix_subscriptionrole_is_default"), "subscriptionrole", ["is_default"], unique=False)
    op.create_index(op.f("ix_subscriptionrole_name"), "subscriptionrole", ["name"], unique=True)
    op.create_table(
        "usersubscription",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usersubscription_id"), "usersubscription", ["id"], unique=False)
    op.create_index(op.f("ix_usersubscription_role_id"), "usersubscription", ["role_id"], unique=False)
    op.create_index(op.f("ix_usersubscription_user_id"), "usersubscription", ["user_id"], unique=True)
    op.drop_index(op.f("ix_file_storage_key"), table_name="file", postgresql_where="(storage_key IS NOT NULL)")
    op.create_index(op.f("ix_file_storage_key"), "file", ["storage_key"], unique=False)
    # ### end Alembic commands ###

    # Seed default subscription roles
    _MB = 1024 * 1024
    _GB = 1024 * _MB
    now = datetime.now(timezone.utc)

    roles_table = sa.table(
        "subscriptionrole",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("storage_limit_bytes", sa.BigInteger()),
        sa.column("max_file_count", sa.Integer()),
        sa.column("max_file_upload_bytes", sa.BigInteger()),
        sa.column("max_parallel_chats", sa.Integer()),
        sa.column("max_sandboxes", sa.Integer()),
        sa.column("is_default", sa.Boolean()),
        sa.column("priority", sa.Integer()),
        sa.column("created_at", sa.TIMESTAMP(timezone=True)),
        sa.column("updated_at", sa.TIMESTAMP(timezone=True)),
    )

    op.bulk_insert(
        roles_table,
        [
            {
                "id": uuid4(),
                "name": "free",
                "display_name": "Free",
                "storage_limit_bytes": 100 * _MB,
                "max_file_count": 200,
                "max_file_upload_bytes": 20 * _MB,
                "max_parallel_chats": 1,
                "max_sandboxes": 0,
                "is_default": True,
                "priority": 0,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid4(),
                "name": "standard",
                "display_name": "Standard",
                "storage_limit_bytes": 1 * _GB,
                "max_file_count": 1000,
                "max_file_upload_bytes": 100 * _MB,
                "max_parallel_chats": 3,
                "max_sandboxes": 1,
                "is_default": False,
                "priority": 1,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid4(),
                "name": "professional",
                "display_name": "Professional",
                "storage_limit_bytes": 10 * _GB,
                "max_file_count": 5000,
                "max_file_upload_bytes": 200 * _MB,
                "max_parallel_chats": 5,
                "max_sandboxes": 2,
                "is_default": False,
                "priority": 2,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": uuid4(),
                "name": "ultra",
                "display_name": "Ultra",
                "storage_limit_bytes": 100 * _GB,
                "max_file_count": 50000,
                "max_file_upload_bytes": 500 * _MB,
                "max_parallel_chats": 10,
                "max_sandboxes": 3,
                "is_default": False,
                "priority": 3,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_storage_key"), table_name="file")
    op.create_index(
        op.f("ix_file_storage_key"), "file", ["storage_key"], unique=True, postgresql_where="(storage_key IS NOT NULL)"
    )
    op.drop_index(op.f("ix_usersubscription_user_id"), table_name="usersubscription")
    op.drop_index(op.f("ix_usersubscription_role_id"), table_name="usersubscription")
    op.drop_index(op.f("ix_usersubscription_id"), table_name="usersubscription")
    op.drop_table("usersubscription")
    op.drop_index(op.f("ix_subscriptionrole_name"), table_name="subscriptionrole")
    op.drop_index(op.f("ix_subscriptionrole_is_default"), table_name="subscriptionrole")
    op.drop_index(op.f("ix_subscriptionrole_id"), table_name="subscriptionrole")
    op.drop_table("subscriptionrole")
    # ### end Alembic commands ###
