"""Add auto_explore_enabled to agent

Revision ID: 2ff4ac5cb897
Revises: eff264cc6a12
Create Date: 2026-03-01 22:35:13.570404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ff4ac5cb897"
down_revision: Union[str, Sequence[str], None] = "eff264cc6a12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("auto_explore_enabled", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent", "auto_explore_enabled")
    # ### end Alembic commands ###
