"""Add chat_share table

Revision ID: 317200ebdca7
Revises: c4e8f1a2b5d7
Create Date: 2026-02-14 13:32:14.511532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "317200ebdca7"
down_revision: Union[str, Sequence[str], None] = "c4e8f1a2b5d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatshare",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("messages_snapshot", sa.JSON(), nullable=False),
        sa.Column("agent_snapshot", sa.JSON(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "REVOKED", "EXPIRED", name="sharestatus"), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chatshare_agent_id"), "chatshare", ["agent_id"], unique=False)
    op.create_index(op.f("ix_chatshare_id"), "chatshare", ["id"], unique=False)
    op.create_index(op.f("ix_chatshare_session_id"), "chatshare", ["session_id"], unique=False)
    op.create_index(op.f("ix_chatshare_token"), "chatshare", ["token"], unique=True)
    op.create_index(op.f("ix_chatshare_topic_id"), "chatshare", ["topic_id"], unique=False)
    op.create_index(op.f("ix_chatshare_user_id"), "chatshare", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chatshare_user_id"), table_name="chatshare")
    op.drop_index(op.f("ix_chatshare_topic_id"), table_name="chatshare")
    op.drop_index(op.f("ix_chatshare_token"), table_name="chatshare")
    op.drop_index(op.f("ix_chatshare_session_id"), table_name="chatshare")
    op.drop_index(op.f("ix_chatshare_id"), table_name="chatshare")
    op.drop_index(op.f("ix_chatshare_agent_id"), table_name="chatshare")
    op.drop_table("chatshare")
    # ### end Alembic commands ###
