"""add column avatar_background_color

Revision ID: 32960112cc33
Revises: d00feda08541
Create Date: 2025-12-18 13:38:31.252131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32960112cc33"
down_revision: Union[str, Sequence[str], None] = "d00feda08541"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent",
        "avatar_background_color",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Avatar background color in hex format",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent",
        "avatar_background_color",
        existing_type=sa.VARCHAR(),
        comment="Avatar background color in hex format",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
