"""add redemption_code_id to internal_applications

Revision ID: 41934871191a
Revises: 0d658196ed81
Create Date: 2026-03-07 03:32:45.548756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41934871191a"
down_revision: Union[str, Sequence[str], None] = "0d658196ed81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("internal_applications", sa.Column("redemption_code_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("internal_applications", "redemption_code_id")
    # ### end Alembic commands ###
