"""Add skill marketplace tables and runners

Revision ID: 44c0b189254e
Revises: a3f7b2c1d4e8
Create Date: 2026-02-25 20:09:13.787940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "44c0b189254e"
down_revision: Union[str, Sequence[str], None] = "a3f7b2c1d4e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runners",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_prefix", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("last_connected_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("os_info", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("work_dir", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_runners_id"), "runners", ["id"], unique=False)
    op.create_index(op.f("ix_runners_user_id"), "runners", ["user_id"], unique=False)
    op.create_table(
        "skilllike",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill_marketplace_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "skill_marketplace_id"),
    )
    op.create_index(op.f("ix_skilllike_skill_marketplace_id"), "skilllike", ["skill_marketplace_id"], unique=False)
    op.create_index(op.f("ix_skilllike_user_id"), "skilllike", ["user_id"], unique=False)
    op.create_table(
        "skillmarketplace",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("active_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scope", sa.String(), server_default="community", nullable=False),
        sa.Column("builtin_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author_display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author_avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("readme", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("forks_count", sa.Integer(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("first_published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skillmarketplace_active_snapshot_id"), "skillmarketplace", ["active_snapshot_id"], unique=False
    )
    op.create_index(op.f("ix_skillmarketplace_builtin_name"), "skillmarketplace", ["builtin_name"], unique=False)
    op.create_index(op.f("ix_skillmarketplace_forks_count"), "skillmarketplace", ["forks_count"], unique=False)
    op.create_index(op.f("ix_skillmarketplace_id"), "skillmarketplace", ["id"], unique=False)
    op.create_index(op.f("ix_skillmarketplace_is_published"), "skillmarketplace", ["is_published"], unique=False)
    op.create_index(op.f("ix_skillmarketplace_likes_count"), "skillmarketplace", ["likes_count"], unique=False)
    op.create_index(op.f("ix_skillmarketplace_name"), "skillmarketplace", ["name"], unique=False)
    op.create_index(op.f("ix_skillmarketplace_scope"), "skillmarketplace", ["scope"], unique=False)
    op.create_index(op.f("ix_skillmarketplace_skill_id"), "skillmarketplace", ["skill_id"], unique=False)
    op.create_index(op.f("ix_skillmarketplace_user_id"), "skillmarketplace", ["user_id"], unique=False)
    op.create_index(
        "uq_skillmarketplace_builtin_name_not_null",
        "skillmarketplace",
        ["builtin_name"],
        unique=True,
        postgresql_where=sa.text("builtin_name IS NOT NULL"),
    )
    op.create_table(
        "skillsnapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("skill_md_content", sa.Text(), nullable=False),
        sa.Column("resource_manifest", sa.JSON(), nullable=True),
        sa.Column("skill_metadata", sa.JSON(), nullable=True),
        sa.Column("commit_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skillsnapshot_id"), "skillsnapshot", ["id"], unique=False)
    op.create_index(op.f("ix_skillsnapshot_skill_id"), "skillsnapshot", ["skill_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skillsnapshot_skill_id"), table_name="skillsnapshot")
    op.drop_index(op.f("ix_skillsnapshot_id"), table_name="skillsnapshot")
    op.drop_table("skillsnapshot")
    op.drop_index(
        "uq_skillmarketplace_builtin_name_not_null",
        table_name="skillmarketplace",
        postgresql_where=sa.text("builtin_name IS NOT NULL"),
    )
    op.drop_index(op.f("ix_skillmarketplace_user_id"), table_name="skillmarketplace")
    op.drop_index(op.f("ix_skillmarketplace_skill_id"), table_name="skillmarketplace")
    op.drop_index(op.f("ix_skillmarketplace_scope"), table_name="skillmarketplace")
    op.drop_index(op.f("ix_skillmarketplace_name"), table_name="skillmarketplace")
    op.drop_index(op.f("ix_skillmarketplace_likes_count"), table_name="skillmarketplace")
    op.drop_index(op.f("ix_skillmarketplace_is_published"), table_name="skillmarketplace")
    op.drop_index(op.f("ix_skillmarketplace_id"), table_name="skillmarketplace")
    op.drop_index(op.f("ix_skillmarketplace_forks_count"), table_name="skillmarketplace")
    op.drop_index(op.f("ix_skillmarketplace_builtin_name"), table_name="skillmarketplace")
    op.drop_index(op.f("ix_skillmarketplace_active_snapshot_id"), table_name="skillmarketplace")
    op.drop_table("skillmarketplace")
    op.drop_index(op.f("ix_skilllike_user_id"), table_name="skilllike")
    op.drop_index(op.f("ix_skilllike_skill_marketplace_id"), table_name="skilllike")
    op.drop_table("skilllike")
    op.drop_index(op.f("ix_runners_user_id"), table_name="runners")
    op.drop_index(op.f("ix_runners_id"), table_name="runners")
    op.drop_table("runners")
    # ### end Alembic commands ###
