"""Add is_pinned to topic

Revision ID: 511109e7a647
Revises: b735fce3552f
Create Date: 2026-02-17 20:49:00.357168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "511109e7a647"
down_revision: Union[str, Sequence[str], None] = "b735fce3552f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("topic", sa.Column("is_pinned", sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "is_pinned")
    # ### end Alembic commands ###
