"""Add developer earning models and consume attribution fields and add skill to agent_snapshot

Revision ID: 678f52c43f41
Revises: c7d8e9f0a1b2
Create Date: 2026-02-24 02:13:56.771933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "678f52c43f41"
down_revision: Union[str, Sequence[str], None] = "c7d8e9f0a1b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creditledger",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("credit_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("direction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column("total_balance_after", sa.BigInteger(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_creditledger_credit_type"), "creditledger", ["credit_type"], unique=False)
    op.create_index(op.f("ix_creditledger_id"), "creditledger", ["id"], unique=False)
    op.create_index(op.f("ix_creditledger_user_id"), "creditledger", ["user_id"], unique=False)
    op.create_table(
        "developerearning",
        sa.Column("developer_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("marketplace_id", sa.Uuid(), nullable=False),
        sa.Column("consumer_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("fork_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("total_consumed", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_devearning_developer_created", "developerearning", ["developer_user_id", "created_at"], unique=False
    )
    op.create_index(
        "idx_devearning_marketplace_created", "developerearning", ["marketplace_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_developerearning_consumer_user_id"), "developerearning", ["consumer_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_developerearning_developer_user_id"), "developerearning", ["developer_user_id"], unique=False
    )
    op.create_index(op.f("ix_developerearning_id"), "developerearning", ["id"], unique=False)
    op.create_index(op.f("ix_developerearning_marketplace_id"), "developerearning", ["marketplace_id"], unique=False)
    op.create_index(op.f("ix_developerearning_status"), "developerearning", ["status"], unique=False)
    op.create_table(
        "developerwallet",
        sa.Column("developer_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("available_balance", sa.BigInteger(), nullable=False),
        sa.Column("total_earned", sa.BigInteger(), nullable=False),
        sa.Column("total_withdrawn", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_developerwallet_developer_user_id"), "developerwallet", ["developer_user_id"], unique=True)
    op.create_index(op.f("ix_developerwallet_id"), "developerwallet", ["id"], unique=False)
    op.add_column("agentsnapshot", sa.Column("skill_configs", sa.JSON(), nullable=True))
    op.add_column("consumerecord", sa.Column("agent_id", sa.Uuid(), nullable=True))
    op.add_column("consumerecord", sa.Column("marketplace_id", sa.Uuid(), nullable=True))
    op.add_column("consumerecord", sa.Column("developer_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f("ix_consumerecord_agent_id"), "consumerecord", ["agent_id"], unique=False)
    op.create_index(op.f("ix_consumerecord_developer_user_id"), "consumerecord", ["developer_user_id"], unique=False)
    op.create_index(op.f("ix_consumerecord_marketplace_id"), "consumerecord", ["marketplace_id"], unique=False)
    op.create_index(op.f("ix_consumerecord_message_id"), "consumerecord", ["message_id"], unique=False)
    op.add_column("userwallet", sa.Column("free_balance", sa.BigInteger(), server_default=sa.text("0"), nullable=False))
    op.add_column("userwallet", sa.Column("paid_balance", sa.BigInteger(), server_default=sa.text("0"), nullable=False))
    op.add_column(
        "userwallet", sa.Column("earned_balance", sa.BigInteger(), server_default=sa.text("0"), nullable=False)
    )
    # Data migration: existing balances without category records fall back to free credits
    op.execute("UPDATE userwallet SET free_balance = virtual_balance WHERE virtual_balance > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userwallet", "earned_balance")
    op.drop_column("userwallet", "paid_balance")
    op.drop_column("userwallet", "free_balance")
    op.drop_index(op.f("ix_consumerecord_message_id"), table_name="consumerecord")
    op.drop_index(op.f("ix_consumerecord_marketplace_id"), table_name="consumerecord")
    op.drop_index(op.f("ix_consumerecord_developer_user_id"), table_name="consumerecord")
    op.drop_index(op.f("ix_consumerecord_agent_id"), table_name="consumerecord")
    op.drop_column("consumerecord", "developer_user_id")
    op.drop_column("consumerecord", "marketplace_id")
    op.drop_column("consumerecord", "agent_id")
    op.drop_column("agentsnapshot", "skill_configs")
    op.drop_index(op.f("ix_developerwallet_id"), table_name="developerwallet")
    op.drop_index(op.f("ix_developerwallet_developer_user_id"), table_name="developerwallet")
    op.drop_table("developerwallet")
    op.drop_index(op.f("ix_developerearning_status"), table_name="developerearning")
    op.drop_index(op.f("ix_developerearning_marketplace_id"), table_name="developerearning")
    op.drop_index(op.f("ix_developerearning_id"), table_name="developerearning")
    op.drop_index(op.f("ix_developerearning_developer_user_id"), table_name="developerearning")
    op.drop_index(op.f("ix_developerearning_consumer_user_id"), table_name="developerearning")
    op.drop_index("idx_devearning_marketplace_created", table_name="developerearning")
    op.drop_index("idx_devearning_developer_created", table_name="developerearning")
    op.drop_table("developerearning")
    op.drop_index(op.f("ix_creditledger_user_id"), table_name="creditledger")
    op.drop_index(op.f("ix_creditledger_id"), table_name="creditledger")
    op.drop_index(op.f("ix_creditledger_credit_type"), table_name="creditledger")
    op.drop_table("creditledger")
    # ### end Alembic commands ###
