"""add root_agent table

Revision ID: 6fe5e1d63039
Revises: d2a1b3c4e5f7
Create Date: 2026-02-19 19:56:56.020280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6fe5e1d63039"
down_revision: Union[str, Sequence[str], None] = "d2a1b3c4e5f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "root_agent",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_root_agent_user_id"),
    )
    op.create_index(op.f("ix_root_agent_agent_id"), "root_agent", ["agent_id"], unique=False)
    op.create_index(op.f("ix_root_agent_id"), "root_agent", ["id"], unique=False)
    op.create_index(op.f("ix_root_agent_user_id"), "root_agent", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_root_agent_user_id"), table_name="root_agent")
    op.drop_index(op.f("ix_root_agent_id"), table_name="root_agent")
    op.drop_index(op.f("ix_root_agent_agent_id"), table_name="root_agent")
    op.drop_table("root_agent")
    # ### end Alembic commands ###
