"""Add user_question_data to messages

Revision ID: 73bab80e41de
Revises: 17aacd78562f
Create Date: 2026-02-28 16:22:57.485664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73bab80e41de"
down_revision: Union[str, Sequence[str], None] = "17aacd78562f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("user_question_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "user_question_data")
    # ### end Alembic commands ###
