"""widen sandbox_backend max_length to 100

Revision ID: 77143cca9539
Revises: 05df78067347
Create Date: 2026-03-02 18:02:05.282133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "77143cca9539"
down_revision: Union[str, Sequence[str], None] = "05df78067347"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session",
        "sandbox_backend",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session",
        "sandbox_backend",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
