"""add purchased_sandbox_slots to user_subscriptions

Revision ID: 7ebae2617bef
Revises: 3fe185da515b
Create Date: 2026-03-01 00:44:39.240655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ebae2617bef"
down_revision: Union[str, Sequence[str], None] = "3fe185da515b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usersubscription", sa.Column("purchased_sandbox_slots", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersubscription", "purchased_sandbox_slots")
    # ### end Alembic commands ###
