"""add scheduled task table

Revision ID: 7feda3a245ad
Revises: 9b6cdd4580e9
Create Date: 2026-02-24 22:53:54.252585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7feda3a245ad"
down_revision: Union[str, Sequence[str], None] = "9b6cdd4580e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduledtask",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
        sa.Column("schedule_type", sa.String(), nullable=False),
        sa.Column("cron_expression", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scheduled_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("celery_task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column("max_runs", sa.Integer(), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scheduledtask_agent_id"), "scheduledtask", ["agent_id"], unique=False)
    op.create_index(op.f("ix_scheduledtask_id"), "scheduledtask", ["id"], unique=False)
    op.create_index(op.f("ix_scheduledtask_status"), "scheduledtask", ["status"], unique=False)
    op.create_index("ix_scheduledtask_status_scheduled_at", "scheduledtask", ["status", "scheduled_at"], unique=False)
    op.create_index(op.f("ix_scheduledtask_user_id"), "scheduledtask", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduledtask_user_id"), table_name="scheduledtask")
    op.drop_index("ix_scheduledtask_status_scheduled_at", table_name="scheduledtask")
    op.drop_index(op.f("ix_scheduledtask_status"), table_name="scheduledtask")
    op.drop_index(op.f("ix_scheduledtask_id"), table_name="scheduledtask")
    op.drop_index(op.f("ix_scheduledtask_agent_id"), table_name="scheduledtask")
    op.drop_table("scheduledtask")
    # ### end Alembic commands ###
