"""add username and total_credits_granted to internal_applications

Revision ID: 847cdfa98ecb
Revises: b794449bbeb9
Create Date: 2026-03-07 17:55:47.199285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "847cdfa98ecb"
down_revision: Union[str, Sequence[str], None] = "b794449bbeb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("internal_applications", sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column(
        "internal_applications", sa.Column("total_credits_granted", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("internal_applications", "total_credits_granted")
    op.drop_column("internal_applications", "username")
    # ### end Alembic commands ###
