"""add full_model_access_expires_at to user_subscriptions

Revision ID: 85f0cf9443d5
Revises: 7ebae2617bef
Create Date: 2026-03-01 01:09:59.568724

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85f0cf9443d5"
down_revision: Union[str, Sequence[str], None] = "7ebae2617bef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usersubscription", sa.Column("full_model_access_expires_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersubscription", "full_model_access_expires_at")
    # ### end Alembic commands ###
