"""Add skill_id to file table and root_folder_id to skill table

Revision ID: 9b6cdd4580e9
Revises: 5480c1ec7b70
Create Date: 2026-02-24 19:33:02.880761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b6cdd4580e9"
down_revision: Union[str, Sequence[str], None] = "5480c1ec7b70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("skill_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_file_skill_id"), "file", ["skill_id"], unique=False)
    op.add_column("skill", sa.Column("root_folder_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skill", "root_folder_id")
    op.drop_index(op.f("ix_file_skill_id"), table_name="file")
    op.drop_column("file", "skill_id")
    # ### end Alembic commands ###
