"""Add push_subscription table

Revision ID: a5ad13fc7be3
Revises: 511109e7a647
Create Date: 2026-02-17 21:14:51.628989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a5ad13fc7be3"
down_revision: Union[str, Sequence[str], None] = "511109e7a647"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("keys_p256dh", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("keys_auth", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_push_sub_endpoint", "push_subscription", ["endpoint"], unique=True)
    op.create_index(op.f("ix_push_subscription_id"), "push_subscription", ["id"], unique=False)
    op.create_index(op.f("ix_push_subscription_user_id"), "push_subscription", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_push_subscription_user_id"), table_name="push_subscription")
    op.drop_index(op.f("ix_push_subscription_id"), table_name="push_subscription")
    op.drop_index("idx_push_sub_endpoint", table_name="push_subscription")
    op.drop_table("push_subscription")
    # ### end Alembic commands ###
