"""add context statistic

Revision ID: b735fce3552f
Revises: b2c3d4e5f6a7
Create Date: 2026-02-17 18:51:04.900144

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b735fce3552f"
down_revision: Union[str, Sequence[str], None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
