"""add parent_id to agent

Revision ID: b794449bbeb9
Revises: c9a3e95cb383
Create Date: 2026-03-07 03:55:54.121107

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b794449bbeb9"
down_revision: Union[str, Sequence[str], None] = "c9a3e95cb383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("parent_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_agent_parent_id"), "agent", ["parent_id"], unique=False)
    # ### end Alembic commands ###

    # Backfill: set parent_id to root agent for all non-root agents
    op.execute(
        """
        UPDATE agent
        SET parent_id = root_agent.agent_id
        FROM root_agent
        WHERE agent.user_id = root_agent.user_id
          AND agent.id != root_agent.agent_id
          AND agent.parent_id IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_parent_id"), table_name="agent")
    op.drop_column("agent", "parent_id")
    # ### end Alembic commands ###
