"""Add agent review table and review counters

Revision ID: c9a3e95cb383
Revises: 41934871191a
Create Date: 2026-03-07 03:52:25.577108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c9a3e95cb383"
down_revision: Union[str, Sequence[str], None] = "41934871191a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agentreview",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("marketplace_id", sa.Uuid(), nullable=False),
        sa.Column("is_positive", sa.Boolean(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("author_display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author_avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agentreview_id"), "agentreview", ["id"], unique=False)
    op.create_index(op.f("ix_agentreview_marketplace_id"), "agentreview", ["marketplace_id"], unique=False)
    op.create_index(op.f("ix_agentreview_user_id"), "agentreview", ["user_id"], unique=False)
    op.create_index("uq_agentreview_user_marketplace", "agentreview", ["user_id", "marketplace_id"], unique=True)
    op.add_column(
        "agentmarketplace", sa.Column("positive_review_count", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "agentmarketplace", sa.Column("negative_review_count", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agentmarketplace", "negative_review_count")
    op.drop_column("agentmarketplace", "positive_review_count")
    op.drop_index("uq_agentreview_user_marketplace", table_name="agentreview")
    op.drop_index(op.f("ix_agentreview_user_id"), table_name="agentreview")
    op.drop_index(op.f("ix_agentreview_marketplace_id"), table_name="agentreview")
    op.drop_index(op.f("ix_agentreview_id"), table_name="agentreview")
    op.drop_table("agentreview")
    # ### end Alembic commands ###
