"""Add allow_fork column to chatshare

Revision ID: d8382cb0b992
Revises: 317200ebdca7
Create Date: 2026-02-14 15:57:57.264973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8382cb0b992"
down_revision: Union[str, Sequence[str], None] = "317200ebdca7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add with server_default so existing rows get False, then drop the default
    op.add_column("chatshare", sa.Column("allow_fork", sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.alter_column("chatshare", "allow_fork", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chatshare", "allow_fork")
    # ### end Alembic commands ###
