"""add gift campaign tables

Revision ID: faf1e2e38675
Revises: 77143cca9539
Create Date: 2026-03-03 23:10:16.756672

"""

from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "faf1e2e38675"
down_revision: Union[str, Sequence[str], None] = "77143cca9539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gift_campaigns",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("total_days", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ends_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gift_campaigns_id"), "gift_campaigns", ["id"], unique=False)
    op.create_index(op.f("ix_gift_campaigns_name"), "gift_campaigns", ["name"], unique=True)
    op.create_table(
        "gift_claims",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("consecutive_days", sa.Integer(), nullable=False),
        sa.Column(
            "reward_data", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claimed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_gift_claim_user_campaign_day", "gift_claims", ["user_id", "campaign_id", "day_number"], unique=True
    )
    op.create_index(op.f("ix_gift_claims_campaign_id"), "gift_claims", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_gift_claims_id"), "gift_claims", ["id"], unique=False)
    op.create_index(op.f("ix_gift_claims_user_id"), "gift_claims", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # Seed beta campaign
    gift_campaigns = sa.table(
        "gift_campaigns",
        sa.column("id", sa.Uuid),
        sa.column("name", sa.String),
        sa.column("display_name_key", sa.String),
        sa.column("description_key", sa.String),
        sa.column("mode", sa.String),
        sa.column("config", postgresql.JSONB),
        sa.column("total_days", sa.Integer),
        sa.column("starts_at", sa.TIMESTAMP(timezone=True)),
        sa.column("ends_at", sa.TIMESTAMP(timezone=True)),
        sa.column("is_active", sa.Boolean),
        sa.column("created_at", sa.TIMESTAMP(timezone=True)),
        sa.column("updated_at", sa.TIMESTAMP(timezone=True)),
    )
    op.bulk_insert(
        gift_campaigns,
        [
            {
                "id": str(uuid4()),
                "name": "beta_2024",
                "display_name_key": "gift.beta2024.title",
                "description_key": "gift.beta2024.description",
                "mode": "daily_credits_with_unlock",
                "config": {
                    "daily_credits": 500,
                    "milestones": [
                        {"consecutive_day": 2, "milestone_name": "standard_unlock", "access_days": 0},
                        {"consecutive_day": 3, "milestone_name": "pro_unlock", "access_days": 0},
                        {"consecutive_day": 5, "milestone_name": "ultra_unlock", "access_days": 30},
                    ],
                },
                "total_days": 30,
                "starts_at": "2024-01-01T00:00:00+00:00",
                "ends_at": "2026-12-31T23:59:59+00:00",
                "is_active": True,
                "created_at": "2024-01-01T00:00:00+00:00",
                "updated_at": "2024-01-01T00:00:00+00:00",
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gift_claims_user_id"), table_name="gift_claims")
    op.drop_index(op.f("ix_gift_claims_id"), table_name="gift_claims")
    op.drop_index(op.f("ix_gift_claims_campaign_id"), table_name="gift_claims")
    op.drop_index("idx_gift_claim_user_campaign_day", table_name="gift_claims")
    op.drop_table("gift_claims")
    op.drop_index(op.f("ix_gift_campaigns_name"), table_name="gift_campaigns")
    op.drop_index(op.f("ix_gift_campaigns_id"), table_name="gift_campaigns")
    op.drop_table("gift_campaigns")
    # ### end Alembic commands ###
