name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry.scienceol.tech
        uses: docker/login-action@v3
        with:
          registry: registry.scienceol.tech
          username: ${{ secrets.SCIENCEOL_REGISTRY_USERNAME }}
          password: ${{ secrets.SCIENCEOL_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build service -t registry.scienceol.tech/sciol/xyzen:latest --push

      - name: Rolling update deployment
        run: |
          kubectl \
            --server=${{ secrets.SCIENCEOL_K8S_SERVER_URL }} \
            --token=${{ secrets.SCIENCEOL_K8S_ADMIN_TOKEN }} \
            --insecure-skip-tls-verify=true \
            rollout restart deployment xyzen -n sciol
