name: Pre-commit Checks

on:
  pull_request:
    branches: [main]
    paths:
      - 'service/**'
      - '.pre-commit-config.yaml'
      - '.github/workflows/pre-commit.yml'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run pre-commit hooks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的 git 历史记录

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 'latest'
          enable-cache: true

      - name: Install dependencies
        working-directory: ./service
        run: |
          echo "Syncing dependencies..."
          uv sync --dev
          echo "Dependencies installed successfully"
          uv run pre-commit install
          echo "Pre-commit hooks installed successfully"
          cd .. && uv run pre-commit run
